name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - release/*

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IMAGE_TAG: latest
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: Set Env
        if: env.BRANCH_NAME != 'master'
        run: echo "IMAGE_TAG=$(echo ${BRANCH_NAME} | tr / - | tr \# - )" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ismdeep
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker release
        run: docker buildx build --platform linux/amd64,linux/arm64 --pull --push --tag "ismdeep/adminer:${IMAGE_TAG}" --tag "ismdeep/adminer:latest" .
